"""initial schema

Revision ID: cea09272c552
Revises: 
Create Date: 2026-02-24 17:14:14.991912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cea09272c552'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('brand_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_brand_roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('brand_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_brand_roles_brand_id'), 'user_brand_roles', ['brand_id'], unique=False)
    op.create_index(op.f('ix_user_brand_roles_user_id'), 'user_brand_roles', ['user_id'], unique=False)
    op.create_table('otb_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('version_name', sa.String(), nullable=False),
    sa.Column('hit', sa.String(), nullable=False),
    sa.Column('drop_month', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otb_versions_project_id'), 'otb_versions', ['project_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('otb_id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('cell_id', sa.String(), nullable=False),
    sa.Column('cell_label', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['otb_id'], ['otb_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_author_id'), 'comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_comments_cell_id'), 'comments', ['cell_id'], unique=False)
    op.create_index(op.f('ix_comments_otb_id'), 'comments', ['otb_id'], unique=False)
    op.create_table('kpi_data',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('otb_id', sa.String(), nullable=False),
    sa.Column('kpi_name', sa.String(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('period_type', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('is_editable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['otb_id'], ['otb_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpi_data_kpi_name'), 'kpi_data', ['kpi_name'], unique=False)
    op.create_index(op.f('ix_kpi_data_otb_id'), 'kpi_data', ['otb_id'], unique=False)
    op.create_table('otb_status_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('otb_id', sa.String(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=False),
    sa.Column('to_status', sa.String(), nullable=False),
    sa.Column('changed_by', sa.String(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['otb_id'], ['otb_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otb_status_history_otb_id'), 'otb_status_history', ['otb_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otb_status_history_otb_id'), table_name='otb_status_history')
    op.drop_table('otb_status_history')
    op.drop_index(op.f('ix_kpi_data_otb_id'), table_name='kpi_data')
    op.drop_index(op.f('ix_kpi_data_kpi_name'), table_name='kpi_data')
    op.drop_table('kpi_data')
    op.drop_index(op.f('ix_comments_otb_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_cell_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_otb_versions_project_id'), table_name='otb_versions')
    op.drop_table('otb_versions')
    op.drop_index(op.f('ix_user_brand_roles_user_id'), table_name='user_brand_roles')
    op.drop_index(op.f('ix_user_brand_roles_brand_id'), table_name='user_brand_roles')
    op.drop_table('user_brand_roles')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('brands')
    # ### end Alembic commands ###
